[package]
name = "saf-backend"
version = "0.1.0"
description = "SAF Backend Django Application"
license = "MIT"
repository = "https://github.com/ahmedsamir45/SAF-Website-backend"

[build]
command = "python -m pip install -e ."

[[command]]
name = "start"
module = "python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = [
    "-m",
    "uvicorn",
    "SAF_backend.asgi:application",
    "--host",
    "0.0.0.0",
    "--port",
    "8080"
]

[[command]]
name = "migrate"
module = "python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["manage.py", "migrate"]

[[command]]
name = "collectstatic"
module = "python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["manage.py", "collectstatic", "--noinput"]

[dependencies]
"python/python" = "^3.13"

[fs]
"/app" = "."

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
DJANGO_SETTINGS_MODULE = "SAF_backend.settings"
ALLOWED_HOSTS = "*"
DEBUG = "False"
