# Generated by Django 5.1.7 on 2025-03-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='kind',
            field=models.CharField(choices=[('JOB', 'Job'), ('INTERN', 'Internship'), ('SCHOLAR', 'Scholarship')], default='JOB', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='target_academic',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('GRADUATE', 'Graduate'), ('BOTH', 'Both')], default='BOTH', max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.weeklyemail'),
        ),
    ]
