# Generated by Django 5.1.7 on 2025-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='confirmed_at',
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
