# Generated by Django 5.1.7 on 2025-04-26 00:32

import activities.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_program_kind_program_target_academic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=activities.models.program_image_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='programemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='programemail',
            name='program',
        ),
        migrations.RemoveField(
            model_name='weeklyuseremail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='weeklyuseremail',
            name='user',
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=activities.models.program_image_path),
        ),
        migrations.AddField(
            model_name='program',
            name='requirements',
            field=models.ManyToManyField(related_name='programs', through='activities.ProgramRequirement', to='activities.requirement'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=activities.models.user_profile_image_path),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='programs',
            field=models.ManyToManyField(related_name='weekly_emails', to='activities.program'),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='users',
            field=models.ManyToManyField(related_name='weekly_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='activities.program'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('RESPONDED', 'Responded')], db_index=True, default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='audience',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], db_index=True, default='BEG', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('BUS', 'Business'), ('ART', 'Art'), ('SCI', 'Science')], db_index=True, default='TECH', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('ON', 'Online'), ('OFF', 'Offline'), ('HY', 'Hybrid')], db_index=True, default='ON', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_enrollment',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_index=True, default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], db_index=True, default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='sent_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='start_date_lte_end_date'),
        ),
        migrations.AddField(
            model_name='programimage',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='activities.program'),
        ),
        migrations.DeleteModel(
            name='ProgramEmail',
        ),
        migrations.DeleteModel(
            name='WeeklyUserEmail',
        ),
    ]
