# Generated by Django 5.1.7 on 2025-10-29 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_newslettersubscription_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='activation_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='activation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['email', 'is_active'], name='activities__email_9cd074_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['activation_code'], name='activities__activat_60594b_idx'),
        ),
    ]
