# Generated by Django 5.1.7 on 2025-10-29 13:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_newslettersubscription_activated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyemail',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Scheduled Email', 'verbose_name_plural': 'Scheduled Emails'},
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='sent_date',
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='users',
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='content',
            field=models.TextField(default='<p>Thank you for subscribing to our newsletter!</p>', help_text='HTML content for the email'),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when the email should be sent'),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='scheduled_hour',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hour (0-23) when the email should be sent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='scheduled_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minute (0-59) when the email should be sent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='scheduled_second',
            field=models.PositiveSmallIntegerField(default=0, help_text='Second (0-59) when the email should be sent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='emails_received', to='activities.newslettersubscription'),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='weekly_emails', to='activities.program'),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='subject',
            field=models.CharField(default='Newsletter Update', max_length=255),
        ),
    ]
