# Generated by Django 5.1.7 on 2025-10-29 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_weeklyemail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyemail',
            options={'ordering': ['-scheduled_for'], 'verbose_name': 'Scheduled Email', 'verbose_name_plural': 'Scheduled Emails'},
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='scheduled_hour',
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='scheduled_minute',
        ),
        migrations.RemoveField(
            model_name='weeklyemail',
            name='scheduled_second',
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='scheduled_for',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the email should be sent'),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('partially_sent', 'Partially Sent')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyemail',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Programs to feature in this email', related_name='weekly_emails', to='activities.program'),
        ),
        migrations.AlterField(
            model_name='weeklyemail',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='Subscribers who should receive this email', related_name='emails_received', to='activities.newslettersubscription'),
        ),
    ]
